Improve stablity and speed
Issue: https://github.com/pdffiller/styleguide-hooks/issues/11

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -1,18 +1,91 @@
-#!/bin/sh
+#!/bin/bash
 
+###########################
+# Branch styleguide check #
+###########################
 
-python3 .git/hooks/pre-commit.py
-ret=$?
-if [ $ret -ne 0 ]; then
-	exit 1
+FOOTER="\n
+Our style guide can be found at:
+https://github.com/pdffiller/styleguide-hooks#branch-naming-format
+
+Quickly rename branch:
+git branch -m NEW_BRANCH_NAME
+"
+
+# Figure out which branch we're on
+BRANCH=$(git symbolic-ref --quiet --short HEAD)
+
+# Don't check if rebase running
+if [ "${BRANCH}" == "" ] ; then
+    # When rebase running we get error "fatal: ref HEAD is not a symbolic ref"
+    # For a more subtle setting in the future can be used next command:
+    # `git rev-parse REBASE_HEAD`
+    exit 0
 fi
+
+ISSUE_TYPE=$(echo ${BRANCH} | cut -d'/' -f1)
+
+ALLOWED_TYPES=(
+    feature
+    improve
+    fix
+    test
+    docs
+    style
+    refactor
+    legacy
+)
+
+for i in `seq 0 ${#ALLOWED_TYPES[@]}`; do
+    if [ "${ALLOWED_TYPES[$i]}" == "${ISSUE_TYPE}" ] ; then
+        break
+    fi
+
+    if [ $i == $((${#ALLOWED_TYPES[@]} - 1)) ] ; then
+        printf "Check branch type. Get '${ISSUE_TYPE}' but it should start from "
+        printf '"%s" ' "${ALLOWED_TYPES[@]}"
+        printf "${FOOTER}"
+        exit 1
+    fi
+done
+
+# Check is branch have any description
+DESCRIPTION=$(echo ${BRANCH} | cut -s -d'/' -f2)
+
+if [ -z "${DESCRIPTION}" ] ; then
+    echo   "Check branch description. In '${BRANCH}' not found any decription"
+    printf "Prefered construction: "
+    printf "issue_type/Jira issue ID/short_description${FOOTER}"
+    exit 1
+fi
+
+
+# Check is jira issue have mistake in it name
+THIRD_ARG=$(echo ${BRANCH} | cut -s -d'/' -f3)
+if [ -n "${THIRD_ARG}" ] ; then
+    ISSUE_NAME=$(echo ${BRANCH} | rev | cut -s -d'/' -f2 | rev)
+
+    JIRA='^[A-Z]{2,}-[0-9]+' # Default format: https://tinyurl.com/yd48c5op
+    if ! [[ ${ISSUE_NAME} =~ ${JIRA} ]] ; then
+        printf "Looks like mistake in Jira issue name.\n"
+        printf "Got '${ISSUE_NAME}', but should be like 'PRJ-1234'"
+        printf "${FOOTER}"
+        exit 1
+    fi
+fi
+
+
+
+######################
+# Default pre-commit #
+######################
 
 if git rev-parse --verify HEAD >/dev/null 2>&1
 then
-	against=HEAD
+    against=HEAD
 else
-	# Initial commit: diff against an empty tree object
-	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
+    # Initial commit: diff against an empty tree object
+    against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
 fi
 
 # If you want to allow non-ASCII filenames set this variable to true.
@@ -25,13 +98,13 @@ allownonascii=$(git config --bool hooks.allownonascii)
 # them from being added to the repository. We exploit the fact that the
 # printable range starts at the space character and ends with tilde.
 if [ "$allownonascii" != "true" ] &&
-	# Note that the use of brackets around a tr range is ok here, (it's
-	# even required, for portability to Solaris 10's /usr/bin/tr), since
-	# the square bracket bytes happen to fall in the designated range.
-	test $(git diff --cached --name-only --diff-filter=A -z $against |
-	  LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
+    # Note that the use of brackets around a tr range is ok here, (it's
+    # even required, for portability to Solaris 10's /usr/bin/tr), since
+    # the square bracket bytes happen to fall in the designated range.
+    test $(git diff --cached --name-only --diff-filter=A -z $against |
+      LC_ALL=C tr -d '[ -~]\0' | wc -c) != 0
 then
-	cat <<\EOF
+    cat <<\EOF
 Error: Attempt to add a non-ASCII file name.
 
 This can cause problems if you want to work with people on other platforms.
@@ -42,7 +115,7 @@ If you know what you are doing you can disable this check using:
 
   git config hooks.allownonascii true
 EOF
-	exit 1
+    exit 1
 fi
 
 # If there are whitespace errors, print the offending file names and fail.
